modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "ALLTHEMONS LICENSE v3.2"

[[mods]]
modId = "z_atm"
version = "5.0"
displayName = "Cobblemon: AllTheMons"
authors = "Lvantic
description = '''
AllTheMons is a collaborative effort from many contributors to add as many Pokemon as possible to Cobblemon.
All of the addons its made of have been modified to ensure that there's no overlap, which prevents any game-breaking bugs/crashes you would experience without it.
'''
logoFile = "pack.png"

[[dependencies.z_atm]]
modId = "cobblemon"
type = "required"
reason = "You're missing like the most important mod for this to work. Install/Update it!"
versionRange = "[1.8.1, )"
ordering = "AFTER"
side = "BOTH"

[[dependencies.z_atm]]
modId = "mega_showdown"
type = "incompatible"
versionRange = "*"
reason = "Download ATM x MSD instead if you use Mega Showdown!"
ordering = "AFTER"
side = "BOTH"

[[dependencies.z_atm]]
modId = "z_atm_x_msd"
type = "incompatible"
versionRange = "*"
reason = "You can only use either AllTheMons OR ATM x MSD, not both!"
ordering = "AFTER"
side = "BOTH"